---
namespace: blueprints
name: vault
version: 0.1.0
readme: README.md
authors:
  - Platform Engineering
description: "Reusable, org-agnostic HashiCorp Vault building blocks (no hidden dependencies)."
license:
  - MIT
tags:
  - security
  - blueprints
  - vault
repository: https://github.com/iac-foundry/ansible-collection-vault
dependencies: {}
build_ignore:
  - .github
  - "*.tar.gz"
  - extensions
