---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart Vault Agent
  ansible.builtin.systemd:
    name: "{{ vault_agent_service_name }}"
    state: restarted
  become: true
